---
name: Checks

on: [push]

env:
  USER: ${{ secrets.USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        env:
          DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
        with:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
